import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.scss";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <main className={styles.main}>
          <section className={styles.section}>
            <header className={styles.header}>
              <h1>Lobe <span>Tour</span></h1>
            <p>
              Build your first machine learning model in ten minutes. No code or
              experience required.
            </p>
            </header>
          <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius iste culpa laudantium quisquam aut dolorem laborum ipsum sed quasi? Vel deserunt expedita fugit totam laudantium sapiente cumque magni sunt eveniet.
          </div>
          <div>
            <p>Train your app with Lobe</p>
            <button className={styles.downloadButton}>Download</button>
          </div>
          </section>
        </main>
        <Footer/>
      </div>
    </>
  );
}
