import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.scss";
import Head from "next/head";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar currentPage="tour" />
        <main className={styles.main}>
          <section className={styles.section}>
            <header className={styles.header}>
              <h1>
                Lobe <span>Tour</span>
              </h1>
              <p>
                Build your first machine learning model in ten minutes. No code
                or experience required.
              </p>
            </header>
            <div>
              <img
                src="https://www.lobe.ai/assets/tour/Video.jpg"
                alt="Learn more about Lobe by watching our tour video."
                className={styles.previewVideoImage}
              />
            </div>
            <div className={styles.downloadSection}>
              <p>Train your app with Lobe</p>
              <button>Download</button>
            </div>
            
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}
